#!/usr/bin/env python

import argparse
import sys
from subprocess import call


def clear_kb_options():
    call(str.split('setxkbmap dvorak -option'))


if __name__ == '__main__':
    parser = argparse.ArgumentParser('kb')
    parser.add_argument('kind', help='Keyboard kind. "default" or "sculpt"',
                        default='default', nargs='?')

    args = parser.parse_args()

    if args.kind == 'default':
        clear_kb_options()
        call(str.split('setxkbmap dvorak -option caps:escape '
                       '-option compose:ralt'))
    elif args.kind == 'sculpt':
        clear_kb_options()
        call(str.split('setxkbmap dvorak -option caps:escape '
                       '-option altwin:swap_lalt_lwin '
                       '-option compose:ralt '
                       '-option altwin:menu'))
